config/routes.rb
Rails.application.routes.draw do

     resources :trips do
      resources :transportations
      resources :accommodations
      resources :todo_lists do
        resources :todo_items
      end
     end

  root "home#index"

    get "/home", to: "home#index"

  resources :users

  resource :session, only: [:new, :create, :destroy]

  resource :calendar, only: [:show]

  get "password", to: "passwords#edit"
  patch "password", to: "passwords#update"
  
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new

    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end

    alias_action :create, :read, :update, :delete, :to => :crud

    can :crud, Trip do |trip|
      user == trip.user
    end

      can :update, User do |user|
      user == user
    end

    can :update, User do |password|
      user == user.password
    end

  end

end

app/models/accommodation.rb
class Accommodation < ApplicationRecord
  # belongs_to :detail
  
  belongs_to :user
  belongs_to :trip

  validates :name, presence: true
  validates :check_in_date, presence: true
  validates :check_in_time, presence: true
  validates :check_out_date, presence: true
  validates :check_out_time, presence: true
  validates :note, length: {maximum: 200}

  geocoded_by :address 
  after_validation :geocode



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list
  belongs_to :user

 

  scope :completed, -> do
    where(completed: true)
  end

  

  
  
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  belongs_to :trip
  belongs_to :user
  has_many :todo_items, dependent: :destroy

  

  def percent_complete
    return 0 if total_items == 0
    (100 * completed_items.to_f / total_items).round(1)
  end

  def completed_items
    @completed_items ||= todo_items.completed.count
  end


  def total_items
    @total_items ||= todo_items.count 
  end

  def status
    case percent_complete.to_i
    when 0
      'Not Started'
    when 100
      'Complete'
    else
      'In Progress'
    end

  end

  def badge_color
    case percent_complete.to_i
    when 0
      'dark'
    when 100
      'success'
    else
      'secondary'
    end

  end

end

app/models/transportation.rb
class Transportation < ApplicationRecord
 
  belongs_to :user
  belongs_to :trip

  validates :company_name, presence: true
  validates :departure, presence: true
  validates :check_in_time, presence: true
  validates :arrival, presence: true
  validates :note, length: {maximum: 200}

  geocoded_by :address 
  after_validation :geocode


end

app/models/trip.rb
class Trip < ApplicationRecord

    belongs_to :user
    has_many :accommodations, dependent: :destroy
    has_many :transportations, dependent: :destroy
    has_many :todo_lists, dependent: :destroy
    has_many :todo_items, through: :todo_lists

    validates :name, presence: true
    validates :departure_date, presence: true
    validates :return_date, presence: true
    

    def start_time
        self.departure_date
    end

    def end_time
        self.return_date
    end
    

    
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :trips, dependent: :destroy

    has_many :accommodations, dependent: :destroy
    has_many :transportations, dependent: :destroy

    has_many :todo_lists, dependent: :destroy
    has_many :todo_items, dependent: :destroy

    # Validations 

    VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: true, format: VALID_EMAIL_REGEX

end

app/controllers/details_controller.rb
class DetailsController < ApplicationController

    def new
    end

    def create
        
    end

    def show

      
    end

    def index

        # # p '******'
        # # p Trip.find params[:trip_id]
        # # p '******'  
        # @trip = Trip.find params[:trip_id]
        # # @accommodations = @trip.accommodations
        # # @accommodation = Accommodation.new 

        # # @trip = @detail.trip
        # @details = @trip.details
        # # @accomodations = @details.accomodations


    end

    def edit
    end

    def update
    end

    def destroy
    end



end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    before_action :find_trip, only: [:edit, :update, :show, :destroy]

    before_action :authenticate_user!

    before_action :authorize_user!, only: [:read, :edit, :update, :destroy]

    def index
        @trips = current_user.trips.order(departure_date: :asc)
    end

    private

    def find_trip
        @trip = Trip.find params[:id]
    end

    def trip_params
        params.require(:trip).permit(:name, :destination, :departure_date, :return_date, :image_url)
    end

    def authorize_user!
        redirect_to root_path, alert: "Not authorized to change post." unless can?(:crud, @trip)
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

    before_action :find_trip, only: [:edit, :update, :show, :destroy]

    before_action :authenticate_user!

    before_action :authorize_user!, only: [:read, :edit, :update, :destroy]

    # Create

    def new
        @trip = Trip.new
    end

    def create
        @trip = Trip.new(trip_params)
        @trip.user = current_user

        if @trip.save 
            flash[:success] = "Trip successfully created!"
            redirect_to @trip
        else
            flash[:error] = "Something went wrong"
            render 'new', status: 303
        end
    end

    # Read

    def index
        @trips = current_user.trips.order(departure_date: :asc)
    end

    def show
        

    end

    # Update

    def edit
    end

    def update
        if @trip.update(trip_params)
            flash[:success] = "Trip successfully updated!"
            redirect_to @trip
        else
            flash[:error] = "Something went wrong"
            render 'edit'
        end
    end

    # Delete

    def destroy
        @trip.destroy
        flash[:success] = "Post successfully deleted."
        redirect_to root_path
    end

    private

    def find_trip
        @trip = Trip.find params[:id]
    end

    def trip_params
        params.require(:trip).permit(:name, :destination, :departure_date, :return_date, :image_url)
    end

    def authorize_user!
        redirect_to root_path, alert: "Not authorized to change post." unless can?(:crud, @trip)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    # Callbacks

    before_action :find_user, only: [:edit, :update]

    # Actions


    # New

        def new
            @user = User.new
        end

        def create
            @user = User.new params.require(:user).permit(
                :first_name,
                :last_name,
                :email,
                :password,
                :password_confirmation
            )

            if @user.save
                session[:user_id] = @user.id
                flash.notice = "Signed Up!"
                redirect_to root_path
            else
                render :new, status: 303
            end
        end

    # Update

        def edit
        end

        def update
            
            if @user.update(user_params)
                flash[:success] = "Profile successfully updated."
                redirect_to root_path 
            else
                redirect_to users_path
                flash[:error] = "Something went wrong."
            end
        end

    private

    def find_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:first_name, :last_name, :email)
    end

end

app/helpers/accommodations_helper.rb
module AccommodationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/transportations_helper.rb
module TransportationsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/trips/_form.html.erb
<div class = "form">
    <%= form_with(model: @trip) do |form| %>

        <% if @trip.errors.any? %>

            <ul>
                <% @trip.errors.full_messages.each do |message| %>

                    <li> <%= message %> </li>

                <% end %>

            </ul>

        <% end %>

        <div class="class=mb-3">
            <%= form.label :name, {class: "form-label"} %>
            <br>
            <%= form.text_field :name, {class: "form-control"} %>
        </div>

        <br>

        <div class="mb-3">
            <%= form.label :destination, {class: "form-label"} %>
            <br>
            <%= form.text_field :destination, {class: "form-control"} %>
        </div>

        <br>

        <div class="mb-3">
            <%= form.label :departure_date, {class: "form-label"} %>
            <br>
            <%= form.date_select :departure_date, {class: "form-control"} %>
        </div>

        <br>

        <div class="mb-3">
            <%= form.label :return_date, {class: "form-label"} %>
            <br>
            <%= form.date_select :return_date, {class: "form-control"} %>
        </div>

        <br>

        <div class="mb-3">
            <%= form.label :image_url, {class: "form-label"} %>
            <br>
            <%= form.text_area :image_url, {class: "form-control"} %>
        </div>

        <br>

        <%= form.submit class:"btn btn-dark" %>

    <% end %>
</div>

app/views/trips/edit.html.erb
<header class = 'header'>
    <h2>Update Trip</h2>
</header>

<div class = "form">
    <%= form_with(model: @trip) do |form| %>

        <% if @trip.errors.any? %>

            <ul>
                <% @trip.errors.full_messages.each do |message| %>

                    <li> <%= message %> </li>

                <% end %>

            </ul>

        <% end %>

        <div class="class=mb-3">
            <%= form.label :name, {class: "form-label"} %>
            <br>
            <%= form.text_field :name, {class: "form-control"} %>
        </div>

        <br>

        <div class="mb-3">
            <%= form.label :destination, {class: "form-label"} %>
            <br>
            <%= form.text_field :destination, {class: "form-control"} %>
        </div>

        <br>

        <div class="mb-3">
            <%= form.label :departure_date, {class: "form-label"} %>
            <br>
            <%= form.date_select :departure_date, {class: "form-control"} %>
        </div>

        <br>

        <div class="mb-3">
            <%= form.label :return_date, {class: "form-label"} %>
            <br>
            <%= form.date_select :return_date, {class: "form-control"} %>
        </div>

        <br>

        <div class="mb-3">
            <%= form.label :image_url, {class: "form-label"} %>
            <br>
            <%= form.text_area :image_url, {class: "form-control"} %>
        </div>
</div>

<div class="d-flex">
    <div class="m-1">
        <%= form.submit 'Update', class:"btn btn-dark" %>
     
        <% end %>
    </div>
    <div class="m-1">
        <%= button_to 'Delete', trip_path(@trip), method: :delete, form: {data: {turbo_confirm: "Are you sure you would like to proceed?"}}, class:"btn btn-danger" %>
     </div>
</div>

app/views/trips/index.html.erb
<% if @trips.length > 0 %>

<h1 class = 'header'> Upcoming Trips</h1>

<br>
  <div>
    <% @trips.each do |trip| %>

      <% if trip.departure_date > DateTime.current %>

        <div class="card mx-auto text-center border-dark index" style = "width: 40vw;">
          <% if trip.image_url%>
          
            <%= image_tag trip.image_url, class:"card-img-top" %>

          <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= trip.name %></h5>
          <p class="card-text"><%= trip.destination %></p>
          <p><%= trip.departure_date.strftime("%B, %d, %Y") %> to <%=trip.return_date.strftime("%B, %d, %Y")%></p>
          <%= link_to 'View', trip_path(trip), class:"btn btn-dark" %>
        </div>
  </div>
    <% end %>
<% end %>

  <h1 class = 'header'> Past Trips</h1>

  <br>

    <div>
    <% @trips.each do |trip| %>

      <% if trip.departure_date < DateTime.current %>

        <div class="card mx-auto text-center border-dark index" style = "width: 40vw;">
          <% if trip.image_url%>
          
            <%= image_tag trip.image_url, class:"card-img-top" %>

          <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= trip.name %></h5>
          <p class="card-text"><%= trip.destination %></p>
          <p><%= trip.departure_date.strftime("%B, %d, %Y") %> to <%=trip.return_date.strftime("%B, %d, %Y")%></p>
          <%= link_to 'View', trip_path(trip), class:"btn btn-dark" %>
        </div>
  </div>
    <% end %>
<% end %>
 <%else%>

    <div class = 'empty_index'>
      <h5>Not trips have been added yet.</h5>
      <br>
      <%= link_to "Let's get started", new_trip_path, class:"btn btn-dark" %>
    </div>


<% end %>
  

app/views/trips/new.html.erb
<header class = 'new_trip_header'>
<h2> New Trip </h2>
</header>

<%= render "form" %>

app/views/trips/show.html.erb
<%= stylesheet_link_tag "show_page", "data-turbo-track": "reload" %>
<body style = "background-image: url(<%= @trip.image_url%>)" class = 'background-image'>
<%= link_to '←', trips_path, class: 'btn back' %>
<div class="card mx-auto border-dark" style="width: 50vw; height:70vh">
  <div class="card-body">
    <div class="card-title"> <h1 ><%= @trip.name %></h1></div>
    <div class="card-subtitle mb-2 text-muted"><h4><%= @trip.destination %></h4></div>
    <p class="card-text"><%= @trip.departure_date.strftime("%B, %d, %Y")%> to <%=@trip.return_date.strftime("%B, %d, %Y")%></p>
    
  <br>
   
  
   <div class="d-grid gap-3 col-12 mx-auto">
      <div class="dropdown-center d-grid gap-3 col-12 mx-auto">
         <button class="btn btn-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          View Details
         </button>
         <ul class="dropdown-menu dropdown-menu-dark ">
            <li><a class="dropdown-item" href="/trips/<%=@trip.id%>/accommodations">Accommodation Details</a></li>
            <li><a class="dropdown-item" href="/trips/<%=@trip.id%>/transportations">Transportation Details</a></li>
         </ul>
   </div>
      <%= link_to 'To-Do', trip_todo_lists_path(@trip), class:"btn btn-dark" %> 
      <%= link_to 'Manage Trip', edit_trip_path(@trip), class:"btn btn-dark" %> 
   </div> 
 </div>
</div>
</body>

app/views/users/edit.html.erb
<header class = 'update_profile_header'>
<h2> Update Your Profile </h2>
</header>

<div class = 'form'>
      <% if @user.errors.any? %>
            <p> <%= @user.errors.full_messages.join(',') %> </p>
      <% end %>

      <%= form_with model: @user do |form| %>

      <form>
            <div class="mb-3">
                  <%= form.label :first_name, 'First Name', {class: "form-label"} %>
                  <br>
                  <%= form.text_field :first_name, {class: "form-control"} %>
            </div>

            <div class="mb-3">
                  <%= form.label :last_name, 'Last Name', {class: "form-label"} %>
                  <br>
                  <%= form.text_field :last_name, {class: "form-control"}  %>
            </div>

            <div class="mb-3">
                  <%= form.label :email, 'Email',{class: "form-label"} %>
                  <br>
                  <%= form.text_field :email, {class: "form-control"} %>
            </div>

            <div class="mb-3">

                  <%= form.label :current_password, 'Current Password', {class: "form-label"} %>
                  <br>
                  <%= form.password_field :current_password, {class: "form-control"} %>
            </div>

            <div class="mb-3">
                  <%= form.label :new_password, 'New Password', {class: "form-label"} %>
                  <br>
                  <%= form.password_field :new_password, {class: "form-control"} %>
            </div>
        
            <div class="mb-3">
                  <%= form.label :new_password_confirmation, 'Password Confirmation', {class: "form-label"} %>
                  <br>
                  <%= form.password_field :new_password_confirmation, {class: "form-control"} %>
            </div>

            <br>

            <%= form.submit "Update", method: :patch, class:"btn btn-dark" %>

      <% end %>
</div>

app/views/users/new.html.erb
<header class = 'header'>
<h1> Sign Up </h1>
</header>

<div class = 'sign_up_form'>
      <% if @user.errors.any? %>
            <p> <%= @user.errors.full_messages.join(',') %> </p>
      <% end %>

      <%= form_with model: @user do |form| %>

      <form>
            <div class="mb-3">
                  <%= form.label :first_name %>
                  <br>
                  <%= form.text_field :first_name %>
            </div>

            <div class="mb-3">
                  <%= form.label :last_name %>
                  <br>
                  <%= form.text_field :last_name %>
            </div>

            <div class="mb-3">
                  <%= form.label :email %>
                  <br>
                  <%= form.text_field :email %>
            </div>

            <div class="mb-3">
                  <%= form.label :password %>
                  <br>
                  <%= form.password_field :password %>
            </div>
  
            <div class="mb-3">
                  <%= form.label :password_confirmation %>
                  <br>
                  <%= form.password_field :password_confirmation %>
            </div>

   
            <%= form.submit "Sign Up", class: "btn btn-dark" %>
      </form>
  
      <% end %>

</div>