config/routes.rb
Rails.application.routes.draw do

     resources :trips do
      resources :transportations
      resources :accommodations
      resources :todo_lists do
        resources :todo_items
      end
     end

  root "home#index"

    get "/home", to: "home#index"

  resources :users

  resource :session, only: [:new, :create, :destroy]

  resource :calendar, only: [:show]

  get "password", to: "passwords#edit"
  patch "password", to: "passwords#update"
  
end

app/models/transportation.rb
class Transportation < ApplicationRecord
 
  belongs_to :user
  belongs_to :trip

  validates :company_name, presence: true
  validates :departure, presence: true
  validates :check_in_time, presence: true
  validates :arrival, presence: true
  validates :note, length: {maximum: 200}

  geocoded_by :address 
  after_validation :geocode


end

app/controllers/transportations_controller.rb
class TransportationsController < ApplicationController
    before_action :find_trip
    before_action :find_transportation, only: [:show, :edit, :update,:destroy]
    before_action :authenticate_user!

    # Create

    def new
        @transportation = Transportation.new
    end

    def create
        @transportation = Transportation.new(transportation_params)
        @transportation.trip = @trip
        @transportation.user = current_user

        if @transportation.save
            flash[:success] = "Successfully created!"
            redirect_to trip_transportations_path
        else
            render @trip, status: 303 
        end
    end

    # Read

    def index
        @transportations = @trip.transportations.order(departure: :asc)
    end

   def show

   end

   # Update

   def edit

   end

   def update
 
        if @transportation.update(transportation_params)
            flash[:success] = "Successfully updated!"
            redirect_to trip_transportation_path
        else
            flash[:error] = "Something went wrong"
            render 'edit'
        end
   end

   # Delete

   def destroy

        @transportation.destroy
        flash[:success] = "Successfully deleted."
        redirect_to trip_transportations_path

   end

   private

    def find_trip
        @trip = Trip.find params[:trip_id] 
    end

    def find_transportation
        @transportation = Transportation.find params[:id]  
    end

    def transportation_params
        params.require(:transportation).permit(:company_name, :address, :departure, :check_in_time, :arrival, :note)
    end

end

app/helpers/transportations_helper.rb
module TransportationsHelper
end

app/views/transportations/_form.html.erb
<div class = "form">
    <%= form_with(model: [@trip, @transportation]) do |form| %>

        <% if @transportation.errors.any? %>

            <ul>
                <% @transportation.errors.full_messages.each do |message| %>

                    <li> <%= message %> </li>

                <% end %>

            </ul>

        <% end %>

        <div class="class=mb-3">
            <%= form.label :company_name, {class: "form-label"} %>
            <br>
            <%= form.text_field :company_name, {class: "form-control"} %>
        </div>

        <br>
        
        <div class="class=mb-3">
            <%= form.label :address, {class: "form-label"} %>
            <br>
            <%= form.text_field :address, {class: "form-control"} %>
        </div>

        <br>


        <div class="mb-3">
            <%= form.label :departure, {class: "form-label"} %>
            <%= form.datetime_select :departure, {class: "form-control"} %>
        </div>
  
        <div class="mb-3">
            <%= form.label :check_in_time, {class: "form-label"} %>
            <%= form.time_select :check_in_time, {class: "form-control"} %>
        </div>
        <div class="mb-3">
            <%= form.label :arrival, {class: "form-label"} %>
            <%= form.datetime_select :arrival, {class: "form-control"} %>
        </div>
        <div class="mb-3">
            <%= form.label :note, {class: "form-label"} %>
            <%= form.text_area :note, {class: "form-control"} %>
        </div>

        <%= form.submit class:"btn btn-dark" %>

    <% end %>
</div>

app/views/transportations/edit.html.erb
<%= link_to '←', :back, class: 'btn back' %>

<header class = 'header'>
    <h2>Update Transportation</h2>
</header>

<div class = "form">
    <%= form_with(model: [@trip, @transportation]) do |form| %>


        <div class="class=mb-3">
            <%= form.label :company_name, {class: "form-label"} %>
            <br>
            <%= form.text_field :company_name, {class: "form-control"} %>
        </div>
        <br>
        <div class="class=mb-3">
            <%= form.label :address, {class: "form-label"} %>
            <br>
            <%= form.text_field :address, {class: "form-control"} %>
        </div>
        <br>
        <div class="mb-3">
            <%= form.label :departure, {class: "form-label"} %>
            <%= form.datetime_select :departure, {class: "form-control"} %>
        </div>
  
        <div class="mb-3">
            <%= form.label :check_in_time, {class: "form-label"} %>
            <%= form.time_select :check_in_time, {class: "form-control"} %>
        </div>
        <div class="mb-3">
            <%= form.label :arrival, {class: "form-label"} %>
            <%= form.datetime_select :arrival, {class: "form-control"} %>
        </div>
        <div class="mb-3">
            <%= form.label :note, {class: "form-label"} %>
            <%= form.text_area :note, {class: "form-control"} %>
        </div>

    
<div class="d-flex">
    <div class="m-1">
        <%= form.submit class:"btn btn-dark" %>
    <% end %>
    </div>
    <div class="m-1">
        <%= button_to 'Delete', trip_transportation_path(@trip, @transportation), method: :delete, form: {data: {turbo_confirm: "Are you sure you would like to proceed?"}}, class:"btn btn-danger" %>
    
    </div>
</div>

app/views/transportations/index.html.erb
<% if @transportations.length > 0 %>
<body style = "background-image: url(<%= @trip.image_url%>)" class = 'background-image'>
<%= link_to '←', trip_path(@trip), class: 'btn back' %>

<div>

 <% @transportations.each do |transportation| %>
      <div class="card mx-auto text-center index border-dark" style = "width: 40vw;">
      
        <div class="card-body">
       
          <h5 class="card-title section" style = 'padding-bottom: 2vh'><%= transportation.company_name %></h5>
          <h5 class="card-subtitle mb-2 text-muted">Check in time:</h5>
          <p class="card-title" style = 'padding-bottom: 2vh'><%= transportation.check_in_time.strftime("%k:%M %p")%></p>
          <h5 class="card-subtitle mb-2 text-muted">Departure:</h5>
          <p class="card-title" style = 'padding-bottom: 2vh'> <%=transportation.departure.strftime("%B, %d, %Y, %k:%M %p")%></p>
          <h5 class="card-subtitle mb-2 text-muted" >Arrival:</h5>
          <p class="card-title" style = 'padding-bottom: 2vh'><%=transportation.arrival.strftime("%B, %d, %Y, %k:%M %p")%></p>

          
          

          <%= link_to 'View', [@trip, transportation], class:"btn btn-dark"%>
        </div>
      </div>

        <% end %>

<div class = 'add_button'><%= link_to 'Add Transportation', new_trip_transportation_path(@trip), class:"btn btn-dark" %></div>

</div>  
</body>

<% else %>

<%= link_to '←', trip_path(@trip), class: 'btn back' %>

    <header class = 'header'>
      <h2>Transportation Details for <%= @trip.name %> </h2>
    </header>
    <div class = 'empty_index'>
      <h5>Plain? Train? Automobile?</h5>
      <br>
      <%= link_to 'Add Transportation', new_trip_transportation_path(@trip), class:"btn btn-dark" %>
    </div>

<% end %>

app/views/transportations/new.html.erb
<%= link_to '←', :back, class: 'btn back' %>

<header class = 'header'>
    <h1>Add Transportation</h1>
</header>
<%= render "form" %>

app/views/transportations/show.html.erb
<%= stylesheet_link_tag "show_page", "data-turbo-track": "reload" %>
<body style = "background-image: url(<%= @transportation.trip.image_url%>)" class = 'background-image'>
<%= link_to '←', trip_transportations_path(@trip), class: 'btn back' %>
<div class="container text-center">
  <div class="row">
    <div class="card-title"><h4 ><%= @transportation.company_name %></h4></div>
    <p class="card-subtitle"><%= @transportation.address %></p>
    <div class="card-text mb-2 text-muted"><h5>Check In</h5></div>
    <p class="card-text"><%=@transportation.check_in_time.strftime("%k:%M %p")%> </p>
    <div class="card-text mb-2 text-muted"><h5>Departure</h5></div>
    <p class="card-text"><%=@transportation.departure.strftime("%B, %d, %Y, %k:%M %p")%> </p>
    <div class="card-text mb-2 text-muted"><h5>Arrival</h5></div>
    <p class="card-text"><%=@transportation.arrival.strftime("%B, %d, %Y, %k:%M %p")%> </p>
    <% if @transportation.note.length > 0 %>
    <div class="card-text mb-2 text-muted"><h5>Notes</h5></div>
    <p class="card-text"><%=@transportation.note%> </p>
    <% end %>
    
   <div>
      <%= link_to 'Manage Transportation', edit_trip_transportation_path(@trip, @transportation), class:"btn btn-dark" %> 
   </div> 
 </div>

  <% if @transportation.latitude && @transportation.longitude%>
  <div class = 'row map' >
 <div id = 'map' style = 'width: 800px; height: 400px;'></div>


<script>
//This is to create the map and copied from: https://github.com/apneadiving/Google-Maps-for-Rails
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers([
        {
        "lat": <%= @transportation.latitude %>, 
        "lng": <%= @transportation.longitude %>,  
        "picture": {
            "width":  32,
            "height": 32
        },
        "infowindow": "<%= @transportation.address %>'s location."
        }
    ]);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(17); //we are adding this to zoom in a bit
});
</script>

</div>

<% end %>
</div>