config/routes.rb
Rails.application.routes.draw do

     resources :trips do
      resources :transportations
      resources :accommodations
      resources :todo_lists do
        resources :todo_items
      end
     end

  root "home#index"

    get "/home", to: "home#index"

  resources :users

  resource :session, only: [:new, :create, :destroy]

  resource :calendar, only: [:show]

  get "password", to: "passwords#edit"
  patch "password", to: "passwords#update"
  
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  belongs_to :trip
  belongs_to :user
  has_many :todo_items, dependent: :destroy

  

  def percent_complete
    return 0 if total_items == 0
    (100 * completed_items.to_f / total_items).round(1)
  end

  def completed_items
    @completed_items ||= todo_items.completed.count
  end


  def total_items
    @total_items ||= todo_items.count 
  end

  def status
    case percent_complete.to_i
    when 0
      'Not Started'
    when 100
      'Complete'
    else
      'In Progress'
    end

  end

  def badge_color
    case percent_complete.to_i
    when 0
      'dark'
    when 100
      'success'
    else
      'secondary'
    end

  end

end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController

    before_action :find_trip
    before_action :find_todo_list, only: [:edit, :update, :show, :destroy]
    before_action :authenticate_user!

    # Create

    def new
        @todo_list = TodoList.new
    end

    def create

        @todo_list = TodoList.new(todo_list_params)
        @todo_list.trip = @trip
        @todo_list.user = current_user
        

        if @todo_list.save
            flash[:success] = "List saved!"
            redirect_to trip_todo_lists_path
        else
            render @trip, status: 303
        end
    end

    # Read

    def index
       
        @todo_lists = @trip.todo_lists.order(created_at: :desc)
        
    end

    def show
        @todo_items = @todo_list.todo_items.order(created_at: :desc)
        @todo_item = TodoItem.new
        
    end

    # Update

    def edit
    end

    def update
        if @todo_list.update(todo_list_params)
            flash[:success] = 'List updated!'
            redirect_to trip_todo_list_path
        else
            flash[:error] = "Something went wrong"
            render 'edit'
        end
    end

    # Destroy

    def destroy
        @todo_list.destroy
        flash[:success] = 'List deleted.'
        redirect_to trip_todo_lists_path
    end

    private

    def find_trip
        @trip = Trip.find params[:trip_id] 

    end

    def find_todo_list
        @todo_list = TodoList.find_by_id params[:id]
    end

    def todo_list_params
        params.require(:todo_list).permit(:description)
    end
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/todo_lists/edit.html.erb
<header class = 'header'>
<h1>Edit To Do List</h1>
</header>

 <%= form_with(model:[@trip, @todo_list]) do |form| %>

    <div class = 'sign_in_form'>
    <div class="class=mb-3">
        <% form.label :description%>
        <%= form.text_area :description, placeholder: "What's this list for?"%> 
    </div>
    <br>
    <br>
    <%= form.submit "Submit", class:"btn btn-dark" %>
 </div>
 <% end %>

app/views/todo_lists/index.html.erb
<% if @todo_lists.length > 0 %>
<body style = "background-image: url(<%= @trip.image_url%>)" class = 'background-image'>
<%= link_to '←', trip_path(@trip), class: 'btn back' %>
<div>

 <% @todo_lists.each do |todo_list| %>
      <div class="card mx-auto text-center index border-dark" style = "width: 40vw;">
      
        <div class="card-body">
       
          <h5 class="card-title"><%= todo_list.description %>
            <h6><span class="badge bg-<%= todo_list.badge_color %>"><%= todo_list.status %></span></h6>
          </h5>

          <div class="progress mb-4">
              <div class="progress-bar progress-bar-striped bg-success" role="progressbar" aria-label="Success striped example" style="width: <%=todo_list.percent_complete%>%" aria-valuenow="<%=todo_list.percent_complete%>%" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
          <%= link_to 'View', [@trip, todo_list], class: 'btn btn-outline-dark'%>
        </div>
      </div>

 <% end %>

<div class = 'add_button'><%= link_to 'New List', new_trip_todo_list_path(@trip), class:"btn btn-dark" %></div>

</div>
</body>

<% else %>

    <header class = 'header'>
      <h2> To Do Lists </h2>
    </header>
    <div class = 'empty_index'>
      <h5>What do you need to pack?</h5>
      <h5>Where would you like to visit?</h5>
      <br>
      <%= link_to 'Make a List', new_trip_todo_list_path(@trip), class:"btn btn-dark"%>
    </div>

<% end %>

app/views/todo_lists/new.html.erb
<%= link_to '←', trip_todo_lists_path(@trip), class: 'btn' %>

<header class = 'header'>
    <h2>New List</h2>
</header>

 <%= form_with(model:[@trip, @todo_list]) do |form| %>
    <div class = 'sign_in_form'>
    <div class="class=mb-3">
        <% form.label :description%>
        <%= form.text_area :description, placeholder: "What's this list for?"%> 
    </div>
    <br>
    <br>
    <%= form.submit "Submit", class:"btn btn-dark" %>
    </div>
 <% end %>

app/views/todo_lists/show.html.erb
  <body style = "background-image: url(<%= @trip.image_url%>)" class = 'background-image' >
    <%= link_to '←', trip_todo_lists_path(@trip), class: 'btn' %>
    <div class = 'container'>
      <div class = 'list-row'>
        <div class = 'col-md-10 col-lg-8 offset-md-1 offset-lg-2'>
          <div class = 'card mt-5 list-card'>
            <div class = "card-header d-flex justify-content-between">
              <div>
                <h5 class = 'm-0'> <b><%= @todo_list.description%></b></h5>
                <p class = 'text-secondary m-0'><small> <%=@todo_list.percent_complete%>% Complete (<%=@todo_list.completed_items%>/<%=@todo_list.total_items%> Todo Items)</small></p>
              </div>
              <div class="d-flex">
                <div class="m-1">
                  <%= link_to 'Edit', edit_trip_todo_list_path(@trip, @todo_list), class:"btn btn-dark" %>
                </div>
                <div class="m-1">
                  <%= button_to 'Delete', trip_todo_list_path(@trip, @todo_list), method: :delete, form: {data: {turbo_confirm: "Are you sure you would like to proceed?"}}, class:"btn btn-danger" %>
                </div>
              </div>

             

              </div>
                <% if @todo_item.errors.any? %>
                  <ul>
                    <% @todo_item.errors.full_messages.each do |message| %>

                    <li> <%= message %> </li>

                  <% end %>

                  </ul>

                <% end %>
                  <div class = "card-body">
                    <div class="progress mb-4">
                      <div class="progress-bar progress-bar-striped bg-success" role="progressbar" aria-label="Success striped example" style="width: <%=@todo_list.percent_complete%>%" aria-valuenow="<%=@todo_list.percent_complete%>%" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <%= form_with(model: [@trip, @todo_list, @todo_item]) do |form| %>
                      <div class = 'input-group mb-4'>
                        <% form.label :description%>
                        <%= form.text_field :description, class: 'form-control', placeholder: "Add item"%> 
                        <div class = 'input-group-append'>
                            <%= form.submit "Add", class:"btn btn-dark input-group-btn" %>
                        </div>
                      </div>
                    <% end %>

                     <ul class = 'list-group'>
                        <% @todo_list.todo_items.each do |todo_item| %>
                          <% if todo_item.completed? %>
                                <li class = 'list-group-item bg-light'>
                                    <div class = "d-flex justify-content-between">
                                      <span class = 'text-muted'>
                                         <em><%= todo_item.description %></em>
                                        </span>
                                        <div class = "d-flex">
                                          <div class="m-1">
                                              <%= form_with(model: [@trip, @todo_list, todo_item]) do |form| %>
                                                <%=form.hidden_field :completed, :value => false, method: :patch %>
                                                <%= form.submit "↻", class:"btn btn-sm btn-dark input-group-btn", method: :patch %>
                                              <%end%>
                                            </div>
                                            <div class="m-1">
                                              <%= button_to 'X', trip_todo_list_todo_item_path(@trip, @todo_list, todo_item), method: :delete, form: {data: {turbo_confirm: "Are you sure you would like to proceed?"}}, class:"btn btn-sm btn-danger" %>
                                            </div>
                                        </div>
                                  </div>
                               </li>
                             <%else%>
                                  <li class = 'list-group-item'>
                                    <div class = "d-flex justify-content-between">
                                      <span>
                                          <%= todo_item.description %> 
                                        </span>
                                        <div class = 'd-flex'>
                                          <div class="m-1">
                                            <%= form_with(model: [@trip, @todo_list, todo_item]) do |form| %>
                                                <%=form.hidden_field :completed, :value => true, method: :patch %>
                                                <%= form.submit "✓", class:"btn btn-sm btn-dark input-group-btn", method: :patch %>
                                            <%end%>
                                          </div>
                                          <div class="m-1">
                                            <%= button_to 'X', trip_todo_list_todo_item_path(@trip, @todo_list, todo_item), method: :delete, form: {data: {turbo_confirm: "Are you sure you would like to proceed?"}}, class:"btn btn-sm btn-danger" %>
                                          </div>
                                        </div>
                                   </div>
                                 </li>
                             <%end%>
                        <% end %>
                     </ul>
                  </div>

               
          

                
                  
                    
                      <%#= button_to 'Delete', trip_todo_list_todo_item_path(@trip, @todo_list, todo_item), method: :delete, form: {data: {turbo_confirm: "Are you sure you would like to proceed?"}}, class:"btn btn-outline-danger" %>

              </div>
            </div>    
        </div>
    </div>
</body> 
 