config/routes.rb
Rails.application.routes.draw do

     resources :trips do
      resources :transportations
      resources :accommodations
      resources :todo_lists do
        resources :todo_items
      end
     end

  root "home#index"

    get "/home", to: "home#index"

  resources :users

  resource :session, only: [:new, :create, :destroy]

  resource :calendar, only: [:show]

  get "password", to: "passwords#edit"
  patch "password", to: "passwords#update"
  
end

app/models/accommodation.rb
class Accommodation < ApplicationRecord
  # belongs_to :detail
  
  belongs_to :user
  belongs_to :trip

  validates :name, presence: true
  validates :check_in_date, presence: true
  validates :check_in_time, presence: true
  validates :check_out_date, presence: true
  validates :check_out_time, presence: true
  validates :note, length: {maximum: 200}

  geocoded_by :address 
  after_validation :geocode



end

app/controllers/accommodations_controller.rb
class AccommodationsController < ApplicationController

    before_action :find_trip
    before_action :find_accommodation, only: [:show, :edit, :update,:destroy]
    before_action :authenticate_user!

   #Create

   def new
    @accommodation = Accommodation.new
   end

   def create

    @accommodation = Accommodation.new(accommodation_params)
    @accommodation.trip = @trip
    @accommodation.user = current_user

    if @accommodation.save
        flash[:success] = "Comment successfully created!"
        redirect_to trip_accommodations_path
    else
        
        render @trip, status: 303 
    end

   end

   #Read

   def index
    @accommodations = @trip.accommodations.order(check_in_date: :desc)
   end

   def show
   
   end

   def edit
   end

   def update

    #   @accommodation.trip = @trip
    #   @accommodation.user = current_user
  
        if @accommodation.update(accommodation_params)
            flash[:success] = "Successfully updated!"
            redirect_to trip_accommodation_path
        else
            flash[:error] = "Something went wrong"
            render 'edit'
        end
   end


   #Destroy

   def destroy

    @accommodation.destroy
    flash[:success] = "Successfully deleted."
    redirect_to trip_accommodations_path

   end

    private

    def find_trip

        @trip = Trip.find params[:trip_id]

    end

    def find_accommodation
         @accommodation = Accommodation.find params[:id]
    end


    def accommodation_params
        params.require(:accommodation).permit(:name, :address, :phone, :email, :check_in_date, :check_out_date, :check_in_time, :check_out_time, :note)
    end

end

app/helpers/accommodations_helper.rb
module AccommodationsHelper
end

app/views/accommodations/_form.html.erb
<div class = "form">
    <%= form_with(model:[@trip, @accommodation]) do |form| %>

        <% if @accommodation.errors.any? %>

            <ul>
                <% @accommodation.errors.full_messages.each do |message| %>

                    <li> <%= message %> </li>

                <% end %>

            </ul>

        <% end %>

        <div class="class=mb-3">
            <%= form.label :name, {class: "form-label"} %>
            <%= form.text_field :name, {class: "form-control"} %>
        </div>
        <div class="class=mb-3">
            <%= form.label :address, {class: "form-label"} %>
            <%= form.text_field :address, {class: "form-control"} %>
        </div>
        <div class="class=mb-3">
            <%= form.label :phone, {class: "form-label"} %>
            <%= form.text_field :phone, {class: "form-control"} %>
        </div>
        <div class="class=mb-3">
            <%= form.label :email, {class: "form-label"} %>
            <%= form.text_field :email, {class: "form-control"} %>
        </div>

        <br>

        <div class="mb-3">
            <%= form.label :check_in_date, {class: "form-label"} %>
            <%= form.date_select :check_in_date, {class: "form-control"} %>
        </div>
        <div class="mb-3">
            <%= form.label :check_out_date, {class: "form-label"} %>
            <%= form.date_select :check_out_date, {class: "form-control"} %>
        </div>
        <div class="mb-3">
            <%= form.label :check_in_time, {class: "form-label"} %>
            <%= form.time_select :check_in_time, {class: "form-control"} %>
        </div>
        <div class="mb-3">
            <%= form.label :check_out_time, {class: "form-label"} %>
            <%= form.time_select :check_out_time, {class: "form-control"} %>
        </div>
        <div class="mb-3">
            <%= form.label :note, {class: "form-label"} %>
            <%= form.text_area :note, {class: "form-control"} %>
        </div>

        <%= form.submit class:"btn btn-dark" %>

    <% end %>
</div>

app/views/accommodations/edit.html.erb
<%= link_to '←', :back, class: 'btn back' %>

<header class = 'header'>
<h2>Update Accommodation</h2>
</header>

<div class = "form">
    <%= form_with(model:[@trip, @accommodation]) do |form| %>



    <div class="class=mb-3">
        <%= form.label :name, {class: "form-label"} %>
        <%= form.text_field :name, {class: "form-control"} %>
    </div>
    <br>
    <div class="class=mb-3">
        <%= form.label :address, {class: "form-label"} %>
        <%= form.text_field :address, {class: "form-control"} %>
    </div>
    <br>
    <div class="class=mb-3">
        <%= form.label :phone, {class: "form-label"} %>
        <%= form.text_field :phone, {class: "form-control"} %>
    </div>
    <br>
    <div class="class=mb-3">
        <%= form.label :email, {class: "form-label"} %>
        <%= form.text_field :email, {class: "form-control"} %>
    </div>

    <br>

    <div class="mb-3">
        <%= form.label :check_in_date, {class: "form-label"} %>
        <%= form.date_select :check_in_date, {class: "form-control"} %>
    </div>
    <div class="mb-3">
        <%= form.label :check_out_date, {class: "form-label"} %>
        <%= form.date_select :check_out_date, {class: "form-control"} %>
    </div>
    <div class="mb-3">
            <%= form.label :check_in_time, {class: "form-label"} %>
            <%= form.time_select :check_in_time, {class: "form-control"} %>
             <%= form.label :check_out_time, {class: "form-label"} %>
            <%= form.time_select :check_out_time, {class: "form-control"} %>
    </div>
    <div class="mb-3">
        <%= form.label :note, {class: "form-label"} %>
        <%= form.text_area :note, {class: "form-control"} %>
    </div>
<div class="d-flex">
    <div class="m-1">
        <%= form.submit class:"btn btn-dark" %>
        <% end %>
   </div>
   <div class="m-1">
        <%= button_to 'Delete', trip_accommodation_path(@trip, @accommodation), method: :delete, form: {data: {turbo_confirm: "Are you sure you would like to proceed?"}}, class:"btn btn-danger" %>
   </div>
 
</div>

app/views/accommodations/index.html.erb
<% if @accommodations.length > 0 %>
<body style = "background-image: url(<%= @trip.image_url%>)" class = 'background-image'>
<%= link_to '←', trip_path(@trip), class: 'btn back' %>
  <div>
  <% @accommodations.each do |accommodation| %>
        <div class="card mx-auto text-center index border-dark" style = "width: 40vw;">
        
          <div class="card-body">
        
            <h4 class="card-title"><%= accommodation.name %></h4>
            <br>
            <h5 class="card-subtitle mb-2 text-muted">Check in:</h5>
            <p class="card-title"><%= accommodation.check_in_date.strftime("%B, %d, %Y")%> at <%= accommodation.check_in_time.strftime("%k:%M %p")%></p>
            <br>
            <h5 class="card-subtitle mb-2 text-muted">Check out:</h5>
            <p class="card-title"><%= accommodation.check_out_date.strftime("%B, %d, %Y")%> at <%= accommodation.check_out_time.strftime("%k:%M %p")%></p>
            <br>
            <%= link_to 'View', [@trip, accommodation], class:"btn btn-dark"%>
          </div>
        </div>

          <% end %>

  <div class = 'add_button'><%= link_to 'Add Accommodation', new_trip_accommodation_path(@trip), class:"btn btn-dark" %></div>

  </div>

  </body>


<% else %>

    <%= link_to '←', trip_path(@trip), class: 'btn back' %>

    <header class = 'header'>
      <h2>Accommodation Details for <%= @trip.name %> </h2>
    </header>
    <div class = 'empty_index'>
      <h5>Where will you be staying?</h5>
      <br>
      <%= link_to 'Add Accommodation', new_trip_accommodation_path(@trip), class:"btn btn-dark" %> 
    </div>

<% end %>

app/views/accommodations/new.html.erb
<%= link_to '←', :back, class: 'btn back' %>
<header class = 'header'>
<h1>New Accommodation</h1>
</header>

<%= render "form" %>

app/views/accommodations/show.html.erb
<%= stylesheet_link_tag "show_page", "data-turbo-track": "reload" %>
<body style = "background-image: url(<%= @accommodation.trip.image_url%>)" class = 'background-image'>
<%= link_to '←', trip_accommodations_path(@trip), class: 'btn back' %>
<div class = 'container text-center'>
  <div class="row">
    <div class="card-title"><h4 ><%= @accommodation.name %></h4></div>
    <p class="card-subtitle"><%= @accommodation.address %></p>
    <div class="card-text mb-2 text-muted"><h5>Check In</h5></div>
    <p class="card-text"><%= @accommodation.check_in_date.strftime("%B, %d, %Y")%> at <%= @accommodation.check_in_time.strftime("%k:%M %p")%> </p>
    <div class="card-text mb-2 text-muted"><h5>Check Out</h5></div>
    <p class="card-text"><%= @accommodation.check_out_date.strftime("%B, %d, %Y")%> at <%= @accommodation.check_out_time.strftime("%k:%M %p")%> </p>
    <% if @accommodation.phone.length > 0 || @accommodation.email.length > 0 %>
    <div class="card-text mb-2 text-muted"><h5>Contact Information</h5></div>
    <% end %>
    <% if @accommodation.phone.length > 0 %>
     <p class="card-text">  Phone: <%= @accommodation.phone%></p><% end %>
     <% if @accommodation.email.length > 0%>
     <p class="card-text"> Email: <%= @accommodation.email%></p>
    <%end%>
    <% if @accommodation.note.length > 0 %>
    <div class="card-text mb-2 text-muted"><h5>Notes</h5></div>
    <p class="card-subtitle"><%= @accommodation.note %></p>
    <%end%>
    
    
   <div >
      <%= link_to 'Manage Accommodation', edit_trip_accommodation_path(@trip, @accommodation), class:"btn btn-dark" %> 
   </div> 
 </div>

 <% if @accommodation.latitude && @accommodation.longitude%>
 <div class = 'row map' >
 <div id = 'map' style = 'width: 800px; height: 400px;'></div>


<script>
//This is to create the map and copied from: https://github.com/apneadiving/Google-Maps-for-Rails
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers([
        {
        "lat": <%= @accommodation.latitude %>, 
        "lng": <%= @accommodation.longitude %>,  
        "picture": {
            "width":  32,
            "height": 32
        },
        "infowindow": "<%= @accommodation.address %>'s location."
        }
    ]);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(17); //we are adding this to zoom in a bit
});
</script>

</div>

<% end %>

</div>